name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2
        with:
          python-versions: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.9.0

      - name: Build wheels
        run: python -m cibuildwheel --platform windows --archs all --output-dir wheelhouse
        env:
          CIBW_BUILD: cp3*-win*
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
